[package]
name = "wasm-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"  # 🔹 Permite async/await no WebAssembly
js-sys = "0.3"  # 🔹 Para manipular bytes no navegador
web-sys = { version = "0.3", features = ["console", "Window", "Response", "Request", "RequestInit", "RequestMode"] }


[lib]
crate-type = ["cdylib", "rlib"]
